version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/app
    container_name: ${PROJECT_NAME}-php-fpm